# Generated by Django 5.2.1 on 2025-05-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
